config/routes.rb
LikeabouseCom::Application.routes.draw do
  root :to => "posts#index"
  get "imprint" => "pages#imprint", as: "imprint"
  get "about" => "pages#about", as: "about"
  get "feed" => "posts#feed", as: "feed", :format => :rss

  resources :posts, :only => [:show] do
    collection do
      get 'feed'
      get 'search'
    end
  end

  resources :categories, :only => [:show]

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :posts, foreign_key: :author_id
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name, :description, :rank
  has_many :posts

  validates :name, presence: true
  validates :rank, presence: true, uniqueness: true

  scope :ordered,     -> { order("rank ASC") }
  scope :with_posts,  -> { includes(:posts) }
  scope :by_post,     ->(post) { where(id: post.category_id) }


  def self.to_show
    self.ordered.with_posts.load.select do |category|
      !category.no_posts?
    end
  end

  def recent_posts(page = nil)
    posts.recent.page(page || 1)
  end

  def no_posts?
    posts.empty?
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :name, :description, :link, :category_id, :author_id

  belongs_to :category
  belongs_to :author, class_name: "AdminUser"

  validates :name, :description, :link, :category_id, :author_id, presence: true

  scope :recent, -> { order("created_at DESC") }
  scope :top, ->(lim) { limit(lim) }
  scope :by_category, ->(category_id) { where(category_id: category_id) }

  paginates_per 16

  def self.search(search)
    where('name LIKE ? OR description LIKE ?', "%#{search}%", "%#{search}%")
  end

  def related_posts
    Post.by_category(Category.by_post(self).first.id).where("id != ?", self.id).recent.page(1)
  end

  def name_to_path
    name.downcase.gsub(/\s+/, "-")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :set_meta_defaults

  helper_method :categories_to_show
  helper :all

  def set_meta_defaults
    @description  = "Short descriptions and links for novice to experienced web developers"
    @keywords     = "ruby, ruby on rails, rails, gems, javascript, css, links, programming, agile, testing"
    @default_title= "Like a Bouse"
    @title        = @default_title

  end

  private
  def categories_to_show
    @categories       ||= Category.to_show
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  layout 'application'

  def show
    @category_id  = params[:id].to_i

    @category     = Category.find_by_id(@category_id)
    @posts        = @category.recent_posts(params[:page])

    @title        = "Like a Bouse - #{@category.name}"

    if request.xhr?
      render "categories/show", category: @category, posts: @posts, layout: nil
    else
      render :show
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  layout "application"

  def imprint
    render 'shared/imprint'
  end

  def about
    @js_files = ["about"]
    render 'shared/about'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  layout "application"

  respond_to :rss, only: [:feed]
  respond_to :html, only: [:index]

  #root
  def index
    page          = params[:page] || 1
    @posts        = Post.recent.page(page)

    if request.xhr?
      render "categories/show", category: @category, posts: @posts, layout: nil
    else
      render template: "categories/show"
    end
  end

  def search
    @posts = Post.search(params[:search]).page(params[:page])

    if request.xhr?
      render "categories/show", category: @category, posts: @posts, layout: nil
    else
      render template: "categories/show"
    end
  end

  def show
    @post     = Post.find(params[:id])

    @title    = "Like a Bouse - #{@post.name}"

    if request.xhr?
      render partial: "posts/post", object: @post
    else
      @category = Category.by_post(@post).first
      @posts    = @post.related_posts

      render :show
    end
  end

  def feed
    @posts = Post.top(25).recent.all
    respond_to do |format|
      format.rss {render layout: false, content_type: "application/rss"}
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def left_categories
    @left_categories ||= categories_to_show[0...(categories_to_show.count/2).ceil]
  end

  def right_categories
    @right_categories ||= categories_to_show - left_categories
  end
end

app/helpers/html_helper.rb
module HtmlHelper
  def link_to_blank(name, link, options = {})
    link_to name, link, options.merge(target: "blank")
  end

  def active_class(condition, klass = "")
    condition ? "#{klass} active".strip : klass
  end
end

app/helpers/layout_helper.rb
module LayoutHelper
  def datetime_string(datetime)
    return "-" if datetime.nil?

    datetime.localtime.strftime "%d.%m.%Y %H:%M"
  end
end

app/helpers/posts_helper.rb
module PostsHelper

  def link_to_category(category)
    link_to category.name, category_path(category), class: "jq_category_link", remote: true
  end

  def link_to_post(post)
    link_to post.name, extended_post_path(post), class: "jq_open_post", remote: true
  end

  def extended_post_path(post)
    "#{post_path(post)}-#{post.name_to_path}"
  end

  def extended_post_url(post)
    "#{post_url(post)}-#{post.name_to_path}"
  end

  def link_to_post_link(post, mode = :link, truncate = true)
    link_text = case mode.to_sym
    when :link
      truncate ? truncate_link(post.link) : post.link
    when :name
      truncate ? truncate(post.name, length: 35) : post.name
    else
      post.name
    end

    link_to_blank link_text, post.link
  end

  def truncate_link(link)
    return "-" if link.nil?

    truncate link.gsub("https://", "").gsub("http://", ""), length: 35
  end

  def post_css_class(post)
    created_at = post.created_at

    if created_at >= 2.days.ago
      "brand-new"
    elsif created_at >= 1.week.ago
      "new"
    else
      "old"
    end
  end

  def post_to_json(post)
    post.as_json(only: [:id, :name]).to_json
  end
end

app/views/categories/_post.html.haml
.post.jq_post_box{id: dom_id(post), data: {post: post_to_json(post)}}
  .post_headline
    %div{class: post_css_class(post)}= "NEW"
    .name= link_to_post post
    .date= datetime_string(post.created_at)
  %hr
  .post_body
    .description= post.description
    .link= link_to_post_link post, :link, true

app/views/categories/_posts.html.haml
- row_index = 0
- posts.in_groups_of(4, false) do |row_posts|
  .row-fluid.jq_posts_row{data: {row: row_index}}
    - row_index += 1
    - for post in row_posts
      .span3
        = render "categories/post", post: post

app/views/categories/show.html.haml
- if @posts.any?
  = render "categories/posts", posts: @posts
  / .hidden
  /   = paginate @posts
- else
  .row-fluid
    .no_entries
      = image_tag('sad_smiley.png')
      = "Leider keine Einträge gefunden"

app/views/layouts/application.html.haml
!!!
%html
  %head
    = render "shared/head"
  %body
    .container-fluid
      .row-fluid
        #header
          = render "shared/header"
      .row-fluid
        #bodyer
          #focus.jq_focus
            = yield :focus
          #content.jq_posts
            = yield
    -# render "shared/develop"
    = render "shared/javascript"

app/views/posts/_post.html.haml
.row-fluid
  .span6.offset3
    .big_post
      .span2
        = link_to image_tag(asset_path("logo_without_text.png")), root_path
      .span10
        .small_logo= link_to image_tag(asset_path("logo_without_text.png")), root_path
        .post_headline
          .name= link_to_post_link post, :name, false
          .date= datetime_string(post.created_at)
        .post_body
          .description= post.description
          .link= link_to_post_link post, :link, false
        .small_logo= link_to image_tag(asset_path("logo_without_text.png")), root_path

app/views/posts/index.html.haml
- if @posts.any?
  = render "categories/posts", posts: @posts
  = paginate @posts
- else
  .row-fluid
    .no_entries
      = image_tag('sad_smiley.png')
      = "Leider keine Einträge gefunden"

app/views/posts/show.html.haml
- content_for :focus do
  = render "posts/post", post: @post
= render "categories/posts", posts: @posts

app/views/shared/_categories.html.haml
.categories
  - categories.each do |category|
    .category{id: dom_id(category), class: (active_category == category ? "active" : "")}
      = link_to_category category

app/views/shared/_develop.html.haml
- git = Git.open Rails.root
- last_commit = git.log.first
#develop{data: {sha: last_commit.sha, message: last_commit.message, author: last_commit.author.name}}

app/views/shared/_head.html.haml
%meta{name: 'viewport', content: 'width=device-width, initial-scale=1.0'}
%meta{name: 'description', content: @description}
%meta{name: 'keywords', content: @keywords}
%title= @title
= favicon_link_tag 'favicon.ico'
= stylesheet_link_tag 'application', media: 'all'
= javascript_include_tag 'application'

app/views/shared/_header.html.haml
.span3
  .logo
    = link_to image_tag(asset_path("logo_transparent_small.png")), root_path
.span2
  = render "shared/categories", categories: left_categories, active_category: @category
.span2
  = render "shared/categories", categories: right_categories, active_category: @category
.span3
  .search_field.jq_search_field
    = form_tag search_posts_path, method: :get, remote: true do
      = text_field_tag :search, params[:search], placeholder: "Search"
.span2
  .links
    = link_to "Imprint", imprint_path
    &nbsp; &nbsp;
    = link_to "About Us", about_path
.span3.offset2
  .social.hidden-phone
    = link_to "//plus.google.com/107164891691789022022?prsrc=3", rel: "publisher", style: "text-decoration: none;", target: '_blank' do
      = image_tag "//ssl.gstatic.com/images/icons/gplus-64.png", alt: "Google+", style: "border:0;width:34px;height:34px;margin-right:5px;margin-top:2px"
    = link_to_blank image_tag('misc/twitter.png'), 'https://twitter.com/#!/Like_a_bouse'
    = link_to_blank image_tag('misc/facebook.png'), 'https://www.facebook.com/pages/Likeabouse/258771540888972', target: '_blank'
    = link_to_blank image_tag('misc/rss.png', class: "rss"), feed_url, target: '_blank'

app/views/shared/_javascript.html.haml
#title.hidden{data: {title: @default_title}}
:javascript
  $(document).ready(function() {
    #{yield :javascript}
  });

- if Rails.env.staging? or Rails.env.production?
  :javascript
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-32988867-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

app/views/shared/_single_big_post.html.haml
/ TODO: Next line must be deleted when done
- post = Post.first
.row-fluid
  .span6.offset3
    .big_post
      .span2
        = link_to image_tag(asset_path("logo_without_text.png")), root_path
      .span10
        .small_logo= link_to image_tag(asset_path("logo_without_text.png")), root_path
        .post_headline
          .name= link_to_post post
          .date= datetime_string(post.created_at)
        .post_body 
          .description= post.description
          .link= link_to_post_link post
        .small_logo= link_to image_tag(asset_path("logo_without_text.png")), root_path

app/views/shared/about.html.haml
.row
  .span2
  .span2
    %h3= image_tag('photos/marko.png', class: "img-circle")
  .span3
    %h2 Marko Hielscher
    %h4 Software Engineer
    %p From Hamburg, Germany
    %p= link_to "Follow me on Twitter", "https://twitter.com/MarkoHiel", target: "_blank"
    %p= link_to "Find me on XING", "http://www.xing.com/profile/Marko_Hielscher", target: "_blank"

  .span2
    %p= image_tag('photos/angelo.jpg', class: "img-circle")
  .span3
    %h2 Angelo Maron
    %h4 Software Engineer
    %p From Hamburg, Germany
    %p= link_to "Follow me on Twitter", "https://twitter.com/mrraffnix", target: "_blank"
    %p= link_to "Find me on XING", "http://www.xing.com/profile/Angelo_Maron", target: "_blank"

app/views/shared/imprint.html.haml
#impressum
  .row-fluid
    .span12
      .span3.offset6
        %h2 Impressum
        %p
          Angaben gemäß § 5 TMG:
        %p
          Angelo Maron
          %br/
          Kunhardtstraße 4
          %br/
          20249 Hamburg
          %br/
        %p
          Marko Hielscher
          %br/
          Wagnerstraße 57
          %br/
          22081 Hamburg
          %br/
      .span2
        %h2 Kontakt:
        %p E-Mail: free(at)likeabouse.com
  .row-fuild
    .span12  
      .span5.box
        %h3 Haftungsausschluss:
        %div
          %strong Haftung für Inhalte
          %p Die Inhalte unserer Seiten wurden mit größter Sorgfalt erstellt. Für die Richtigkeit, Vollständigkeit und Aktualität der Inhalte können wir jedoch keine Gewähr übernehmen. Als Diensteanbieter sind wir gemäß § 7 Abs.1 TMG für eigene Inhalte auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich. Nach §§ 8 bis 10 TMG sind wir als Diensteanbieter jedoch nicht verpflichtet, übermittelte oder gespeicherte fremde Informationen zu überwachen oder nach Umständen zu forschen, die auf eine rechtswidrige Tätigkeit hinweisen. Verpflichtungen zur Entfernung oder Sperrung der Nutzung von Informationen nach den allgemeinen Gesetzen bleiben hiervon unberührt. Eine diesbezügliche Haftung ist jedoch erst ab dem Zeitpunkt der Kenntnis einer konkreten Rechtsverletzung möglich. Bei Bekanntwerden von entsprechenden Rechtsverletzungen werden wir diese Inhalte umgehend entfernen.

          %strong Haftung für Links
          %p Unser Angebot enthält Links zu externen Webseiten Dritter, auf deren Inhalte wir keinen Einfluss haben. Deshalb können wir für diese fremden Inhalte auch keine Gewähr übernehmen. Für die Inhalte der verlinkten Seiten ist stets der jeweilige Anbieter oder Betreiber der Seiten verantwortlich. Die verlinkten Seiten wurden zum Zeitpunkt der Verlinkung auf mögliche Rechtsverstöße überprüft. Rechtswidrige Inhalte waren zum Zeitpunkt der Verlinkung nicht erkennbar. Eine permanente inhaltliche Kontrolle der verlinkten Seiten ist jedoch ohne konkrete Anhaltspunkte einer Rechtsverletzung nicht zumutbar. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Links umgehend entfernen.

          %strong Urheberrecht
          %p Die durch die Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten unterliegen dem deutschen Urheberrecht. Die Vervielfältigung, Bearbeitung, Verbreitung und jede Art der Verwertung außerhalb der Grenzen des Urheberrechtes bedürfen der schriftlichen Zustimmung des jeweiligen Autors bzw. Erstellers. Downloads und Kopien dieser Seite sind nur für den privaten, nicht kommerziellen Gebrauch gestattet. Soweit die Inhalte auf dieser Seite nicht vom Betreiber erstellt wurden, werden die Urheberrechte Dritter beachtet. Insbesondere werden Inhalte Dritter als solche gekennzeichnet. Sollten Sie trotzdem auf eine Urheberrechtsverletzung aufmerksam werden, bitten wir um einen entsprechenden Hinweis. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Inhalte umgehend entfernen.

          %strong Datenschutz
          %p Die Nutzung unserer Webseite ist in der Regel ohne Angabe personenbezogener Daten möglich. Soweit auf unseren Seiten personenbezogene Daten (beispielsweise Name, Anschrift oder eMail-Adressen) erhoben werden, erfolgt dies, soweit möglich, stets auf freiwilliger Basis. Diese Daten werden ohne Ihre ausdrückliche Zustimmung nicht an Dritte weitergegeben.
          %p Wir weisen darauf hin, dass die Datenübertragung im Internet (z.B. bei der Kommunikation per E-Mail) Sicherheitslücken aufweisen kann. Ein lückenloser Schutz der Daten vor dem Zugriff durch Dritte ist nicht möglich.
          %p Der Nutzung von im Rahmen der Impressumspflicht veröffentlichten Kontaktdaten durch Dritte zur Übersendung von nicht ausdrücklich angeforderter Werbung und Informationsmaterialien wird hiermit ausdrücklich widersprochen. Die Betreiber der Seiten behalten sich ausdrücklich rechtliche Schritte im Falle der unverlangten Zusendung von Werbeinformationen, etwa durch Spam-Mails, vor.
      .span6.box
        %h3 Datenschutzerklärung für die Nutzung von Facebook-Plugins (Like-Button)
        %p 
          Auf unseren Seiten sind Plugins des sozialen Netzwerks Facebook, 1601 South California Avenue, Palo Alto, CA 94304, USA integriert. Die Facebook-Plugins erkennen Sie an dem Facebook-Logo oder dem "Like-Button" ("Gefällt mir") auf unserer Seite. Eine Übersicht über die Facebook-Plugins finden Sie hier:
          = succeed "." do
            %a{:href => "http://developers.facebook.com/docs/plugins/", :target => "_blank"} http://developers.facebook.com/docs/plugins/
          %br/
          Wenn Sie unsere Seiten besuchen, wird über das Plugin eine direkte Verbindung zwischen Ihrem Browser und dem Facebook-Server hergestellt. Facebook erhält dadurch die Information, dass Sie mit Ihrer IP-Adresse unsere Seite besucht haben. Wenn Sie den Facebook "Like-Button" anklicken während Sie in Ihrem Facebook-Account eingeloggt sind, können Sie die Inhalte unserer Seiten auf Ihrem Facebook-Profil verlinken. Dadurch kann Facebook den Besuch unserer Seiten Ihrem Benutzerkonto zuordnen. Wir weisen darauf hin, dass wir als Anbieter der Seiten keine Kenntnis vom Inhalt der übermittelten Daten sowie deren Nutzung durch Facebook erhalten. Weitere Informationen hierzu finden Sie in der Datenschutzerklärung von facebook unter
          %a{:href => "http://de-de.facebook.com/policy.php", :target => "_blank"} http://de-de.facebook.com/policy.php
          %p Wenn Sie nicht wünschen, dass Facebook den Besuch unserer Seiten Ihrem Facebook-Nutzerkonto zuordnen kann, loggen Sie sich bitte aus Ihrem Facebook-Benutzerkonto aus.
      
      .span6.box  
        %h3 Datenschutzerklärung für die Nutzung von Google +1
        %i Erfassung und Weitergabe von Informationen:
        %br/
        Mithilfe der Google +1-Schaltfläche können Sie Informationen weltweit veröffentlichen. über die Google +1-Schaltfläche erhalten Sie und andere Nutzer personalisierte Inhalte von Google und unseren Partnern. Google speichert sowohl die Information, dass Sie für einen Inhalt +1 gegeben haben, als auch Informationen über die Seite, die Sie beim Klicken auf +1 angesehen haben. Ihre +1 können als Hinweise zusammen mit Ihrem Profilnamen und Ihrem Foto in Google-Diensten, wie etwa in Suchergebnissen oder in Ihrem Google-Profil, oder an anderen Stellen auf Websites und Anzeigen im Internet eingeblendet werden.
        %br/
        Google zeichnet Informationen über Ihre +1-Aktivitäten auf, um die Google-Dienste für Sie und andere zu verbessern. Um die Google +1-Schaltfläche verwenden zu können, benötigen Sie ein weltweit sichtbares, öffentliches Google-Profil, das zumindest den für das Profil gewählten Namen enthalten muss. Dieser Name wird in allen Google-Diensten verwendet. In manchen Fällen kann dieser Name auch einen anderen Namen ersetzen, den Sie beim Teilen von Inhalten über Ihr Google-Konto verwendet haben. Die Identität Ihres Google-Profils kann Nutzern angezeigt werden, die Ihre E-Mail-Adresse kennen oder über andere identifizierende Informationen von Ihnen verfügen.
        %br/
        %br/
        %i Verwendung der erfassten Informationen:
        %br/
        %p 
          Neben den oben erläuterten Verwendungszwecken werden die von Ihnen bereitgestellten Informationen gemäß den geltenden Google-Datenschutzbestimmungen genutzt. Google veröffentlicht möglicherweise zusammengefasste Statistiken über die +1-Aktivitäten der Nutzer bzw. gibt diese an Nutzer und Partner weiter, wie etwa Publisher, Inserenten oder verbundene Websites.       
        %strong Quellverweis:
        %a{:href => "http://www.google.com/intl/de/+/policy/+1button.html", :target => "_blank"} Datenschutzerklärung für Google +1
      .span6.box  
        %p
          %strong Datenschutzerklärung für die Nutzung von Twitter
        %p Auf unseren Seiten sind Funktionen des Dienstes Twitter eingebunden. Diese Funktionen werden angeboten durch die Twitter Inc., 795 Folsom St., Suite 600, San Francisco, CA 94107, USA. Durch das Benutzen von Twitter und der Funktion "Re-Tweet" werden die von Ihnen besuchten Webseiten mit Ihrem Twitter-Account verknüpft und anderen Nutzern bekannt gegeben. Dabei werden auch Daten an Twitter übertragen.
        %p
          Wir weisen darauf hin, dass wir als Anbieter der Seiten keine Kenntnis vom Inhalt der übermittelten Daten sowie deren Nutzung durch Twitter erhalten. Weitere Informationen hierzu finden Sie in der Datenschutzerklärung von Twitter unter
          = succeed "." do
            %a{:href => "http://twitter.com/privacy", :target => "_blank"} http://twitter.com/privacy
        %p
          Ihre Datenschutzeinstellungen bei Twitter können Sie in den Konto-Einstellungen unter
          %a{:href => "http://twitter.com/account/settings", :target => "_blank"} http://twitter.com/account/settings
          ändern.
        %strong Quellverweis:
        %a{:href => "http://twitter.com/privacy", :target => "_blank"} Twitter Bedingungen       